In [1]:
import twint
import nest_asyncio
from lib import bittwint
import pandas as pd
import matplotlib.pyplot as plt

nest_asyncio.apply()

In [2]:
df = bittwint.scrape_twitter(
    "bitcoin", 
    10000, 
    "2021-08-01",
    until="2021-09-01",
    verified=False, 
    output="../data/raw/bitcoin_unverified_tweets_6.csv"
)

df.head()

  0%|          | 0/32 [00:00<?, ?it/s]

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1421984085187072000,1421982610373349377,1.627862e+12,2021-08-01 19:59:59,-0500,,@APompliano CashApp fees for buying/selling Bi...,en,[],[],...,,,,,,"[{'screen_name': 'APompliano', 'name': 'Pomp ðŸŒª...",,,,
1,1421984047757209605,1421984047757209605,1.627862e+12,2021-08-01 19:59:50,-0500,,You can still get $39950 for a bitcoin,en,[],[],...,,,,,,[],,,,
2,1421984003947745283,1421982277811253249,1.627862e+12,2021-08-01 19:59:40,-0500,,@llenas_miguel Bitcoin.,en,[],[],...,,,,,,"[{'screen_name': 'llenas_miguel', 'name': 'Mig...",,,,
3,1421984000969748482,1421861313207169025,1.627862e+12,2021-08-01 19:59:39,-0500,,@FiftySatFinance Iâ€™ve been buying Bitcoin with...,en,[],[],...,,,,,,"[{'screen_name': 'FiftySatFinance', 'name': 'F...",,,,
4,1421984000592252938,1421828424092590086,1.627862e+12,2021-08-01 19:59:39,-0500,,@LeeSmit97097126 @ShibaInfluencer They have se...,en,[],[],...,,,,,,"[{'screen_name': 'LeeSmit97097126', 'name': 'L...",,,,

In [3]:
# fix, ax = plt.subplots(figsize=(10, 7))
# ax.bar(date_count['date'], date_count['id'])
# plt.show()

In [4]:
df

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1421984085187072000,1421982610373349377,1.627862e+12,2021-08-01 19:59:59,-0500,,@APompliano CashApp fees for buying/selling Bi...,en,[],[],...,,,,,,"[{'screen_name': 'APompliano', 'name': 'Pomp ðŸŒª...",,,,
1,1421984047757209605,1421984047757209605,1.627862e+12,2021-08-01 19:59:50,-0500,,You can still get $39950 for a bitcoin,en,[],[],...,,,,,,[],,,,
2,1421984003947745283,1421982277811253249,1.627862e+12,2021-08-01 19:59:40,-0500,,@llenas_miguel Bitcoin.,en,[],[],...,,,,,,"[{'screen_name': 'llenas_miguel', 'name': 'Mig...",,,,
3,1421984000969748482,1421861313207169025,1.627862e+12,2021-08-01 19:59:39,-0500,,@FiftySatFinance Iâ€™ve been buying Bitcoin with...,en,[],[],...,,,,,,"[{'screen_name': 'FiftySatFinance', 'name': 'F...",,,,
4,1421984000592252938,1421828424092590086,1.627862e+12,2021-08-01 19:59:39,-0500,,@LeeSmit97097126 @ShibaInfluencer They have se...,en,[],[],...,,,,,,"[{'screen_name': 'LeeSmit97097126', 'name': 'L...",,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313591,1433128457102372865,1433128457102372865,1.630519e+12,2021-09-01 14:03:45,-0500,,"Crypto utilization &amp; adoption continues, a...",en,[],[],...,,,,,,[],,,,
313592,1433128448394936324,1433128448394936324,1.630519e+12,2021-09-01 14:03:42,-0500,,Welcome to the #getUmbrel tribe. Full #Bitcoin...,en,"[getumbrel, bitcoin, btc]",[],...,,,,,,[],,,,
313593,1433128445433765889,1433073757124452359,1.630519e+12,2021-09-01 14:03:42,-0500,,@Bilthon @alpacasw @Bitcoinfuture9 @AaronvanW ...,en,[],[],...,,,,,,"[{'screen_name': 'Bilthon', 'name': 'Bilthon [...",,,,
313594,1433128434549547014,1433128434549547014,1.630519e+12,2021-09-01 14:03:39,-0500,,Our reality is full of paradoxes. Chaos and or...,en,[bitcoin],[],...,,,,,,[],,,,
313595,1433128433475747845,1433128433475747845,1.630519e+12,2021-09-01 14:03:39,-0500,,"9- and 14-year-old Bitcoin, ETH, RVN Miners â€˜M...",en,[],[],...,,,,,,[],,,,